[qa]
connection_max = "100"
enabled = "true"
db = "53f51b0d-63ab-46d1-b941-d8d8d767e07a"
collectionName = "tickets"
dbServiceName = "mongodb"
userName = "5eba60e2-e53e-42de-99fe-56d09bded801"
password = "0fa6a586710f8ecb5687252f9df18811"
server = "10.54.141.53"
uri = "mongodb://5eba60e2-e53e-42de-99fe-56d09bded801:0fa6a586710f8ecb5687252f9df18811@10.54.141.53:27017/53f51b0d-63ab-46d1-b941-d8d8d767e07a"
port = "27017"

[staging]
connection_max = "200"
enabled = "true"
dbServiceName = "mongodb"

[production]
connection_max = "5000"
enabled = "true"
dbServiceName = "mongodb"
uri = "mongodb://5eba60e2-e53e-42de-99fe-56d09bded801:0fa6a586710f8ecb5687252f9df18811@10.54.141.53:27017/53f51b0d-63ab-46d1-b941-d8d8d767e07a"


[local]
server = "127.0.0.1"
port = "27017"
connection_max = "100"
enabled = "true"
db = "d7a38796-8624-4a42-b438-a281097aaee5"
collectionName = "tickets"
dbServiceName = "mongodb"

[cure]
userName= "csdatapull"
password= "Comc@stCl0ud"
server= "172.26.46.176"
[cure."options"]
port= "4951"
database= "UPWARE_REPORTING"
[cure."debug"]
packet= "true"
data= "true"
payload= "true"
token= "true"
log= "true"

#EndDayOffSet should be calculated from BegindayOffSet. When offset by 2 days(-2)
#if endDayOffSet is today then it should be (2).
#Make them equal to have date from one day only.

[Dateoffset]
BeginDayOffSet = 1
EndDayOffSet = 1

#[SQLQuery]
#query = '"SELECT ID, FO_OwnerUserID,  FO_AckDate, FO_RemedyTicketNo, To_SubmitterName, TO_SubmitterEmail, TO_SubmitterContactNo,FO_SubmissionDate, FO_Severity, FO_Priority, UD_UserCompanyName, MD_SubmissionEmail, UD_UserLogonEmail,MD_DefectType, UC_ContactName, UC_ContactEmail, UC_BestTimeToContact, UC_UserContactNo, UC_PermissionToAccess, ID_Product, ID_TypeOfIssue, ID_OS, ID_Browser, ID_FoundThroghSSR, ID_SRREmail, ID_IssueSummary, MD_SaleAmount, ID_StepsToReproduce, ID_Comment, MD_SLA, #MD_Status, MD_NotifySLA, MD_Outlier, MD_CustImpact from " + this.sourceTableName + " where FO_SubmissionDate between '" + this.queryBeginDate + "' AND '" + this.queryEndDate + "'";'
