[qa]
connection_max = "100"
enabled = "true"
db = "a31836de-4f8e-4cc8-b8f3-f429b256fa8f"
collectionName = "tickets"
dbServiceName = "mongodb"
userName = "c8509889-1b08-4136-872c-9805fc2ca6b8"
password = "70b1ff24b6eb19888dc920edbc35c3c6"
server = "172.24.68.198"
uri = "mongodb://c8509889-1b08-4136-872c-9805fc2ca6b8:70b1ff24b6eb19888dc920edbc35c3c6@172.24.68.198:27017/a31836de-4f8e-4cc8-b8f3-f429b256fa8f"
port = "27017"

[production]
connection_max = "5000"
enabled = "true"
db ="442d032b-b605-409f-93a6-c7c8095c42de"
collectionName = "tickets"
dbServiceName = "mongodb"
userName = "ac03b35a-83f8-4bd3-bc54-72abe5519d17"
password = "c956b6add22e02717eb0fd3fc890664b"
server = "172.24.68.198"
uri = "mongodb://ac03b35a-83f8-4bd3-bc54-72abe5519d17:c956b6add22e02717eb0fd3fc890664b@172.24.68.198:27017/442d032b-b605-409f-93a6-c7c8095c42de"

[local]
server = "127.0.0.1"
port = "27017"
connection_max = "100"
enabled = "true"
db = "d7a38796-8624-4a42-b438-a281097aaee5"
collectionName = "tickets"
dbServiceName = "mongodb"

[cure]
userName= "csdatapull"
password= "Comc@stCl0ud"
server= "172.26.46.176"
port= "4951"
database= "UPWARE_REPORTING"
packet= "true"
data= "true"
payload= "true"
token= "true"
log= "true"

#EndDayOffSet should be calculated from BegindayOffSet. When offset by 2 days(-2)
#if endDayOffSet is today then it should be (2).
#Make them equal to have date from one day only.

[Dateoffset]
BeginDayOffSet = 1
EndDayOffSet = 1
