[qa]
host = "172.24.68.198"
port = "27017"
connection_max = "100"
enabled = "true"
db = "d995ad7e-c94c-4d90-b35e-d503fe54ab7d"
collectionName = "tickets"
dbServiceName = "mongodb"
username = "fdbfd462-36c5-46d7-a307-c1bc99d074b8"
password = "3102d704efae26955a01ffa794e5bb46"

[staging]
connection_max = "5000"
enabled = "true"
dbServiceName = "mongodb"
db = "cure"

[production]
connection_max = "5000"
enabled = "true"
dbServiceName = "mongodb"
db = "cure"

[local]
host = "127.0.0.1"
port = "27017"
connection_max = "100"
enabled = "true"
db = "cure"
collectionName = "tickets"
dbServiceName = "mongodb"

[cure]
