[qa]
connection_max = ""
enabled = ""
db = ""
collectionName = ""
dbServiceName = ""
userName = ""
password = ""
server = ""
uri = ""
port = ""

[staging]
connection_max = ""
enabled = "true"
dbServiceName = ""
uri = ""

[production]
connection_max = ""
enabled = "true"
dbServiceName = ""
uri = ""


[local]
server = ""
port = ""
connection_max = ""
enabled = ""
db = ""
collectionName = ""
dbServiceName = ""
uri = ""
